version: "3.3"
services:
  ds:
    env_file:
      ./dev/dev.env
    volumes:
      - "./devdb:/app/db"
  kdc:
    env_file:
      ./dev/dev.env
    volumes:
      - "./devdb:/app/db"
  kadmin:
    env_file:
      ./dev/dev.env
    volumes:
      - "./devdb:/app/db"
  dev:
    build:
      target: dev
    env_file:
      ./dev/dev.env
    volumes:
      - "./devdb:/app/db"
      - slaprun:/var/run/slapd
