version: "3.3"
services:
  ds:
    restart: unless-stopped
    build:
      target: ds
    volumes:
      - slaprun:/var/run/slapd
    networks:
      - iamnet
    depends_on:
      infra-ca:
        condition: service_healthy
  kdc:
    restart: unless-stopped
    build:
      target: kdc
    depends_on:
      infra-ca:
        condition: service_healthy
      user-ca:
        condition: service_healthy
      ds:
        condition: service_started
    volumes:
      - slaprun:/var/run/slapd
    networks:
      - iamnet
  kadmin:
    restart: unless-stopped
    build:
      target: kadmin
    depends_on:
      - ds
      - kdc
    ports:
      - "127.0.0.1:749:749/udp"
    volumes:
      - slaprun:/var/run/slapd
    networks:
      - iamnet
  prov-ca:
    build:
      target: online-ca
    networks:
      - iamnet
  infra-ca:
    build:
      target: online-ca
    networks:
      - iamnet
  user-ca:
    build:
      target: online-ca
    networks:
      - iamnet
volumes:
  slaprun:
networks:
  iamnet: