version: "3.3"
services:
  ds:
    restart: unless-stopped
    build:
      target: ds
    volumes:
      - slaprun:/var/run/slapd
    networks:
      - iamnet
  kdc:
    restart: unless-stopped
    build:
      target: kdc
    depends_on:
      ds:
        condition: service_healthy
    volumes:
      - slaprun:/var/run/slapd
    networks:
      - iamnet
  kadmin:
    restart: unless-stopped
    build:
      target: kadmin
    depends_on:
      ds:
        condition: service_healthy
      kdc:
        condition: service_healthy
    ports:
      - "127.0.0.1:749:749/udp"
    volumes:
      - slaprun:/var/run/slapd
    networks:
      - iamnet
volumes:
  slaprun:
networks:
  iamnet: