version: "3.3"
services:
  ds:
    env_file:
      ./dev/dev.env
    volumes:
      - "./dev/data/ds:/app/db"
  kdc:
    env_file:
      ./dev/dev.env
    environment:
      IAM_KADMINDIR: /app/kadmin-data
      IAM_SECRETSDIR: /app/secrets
    volumes:
      - "./dev/data/secrets:/app/secrets"
      - "./dev/data/kdc:/app/db"
      - "./dev/data/kadmin:/app/kadmin-data"
  kadmin:
    env_file:
      ./dev/dev.env
    volumes:
      - "./dev/data/kadmin:/app/db"
  dev:
    build:
      target: dev
    env_file:
      ./dev/dev.env
    volumes:
      - slaprun:/var/run/slapd
      - "./:/workspace:cached"
      - home:/me
volumes:
  home:
