version: "3.3"
services:
  ds:
    env_file:
      ./dev/dev.env
    volumes:
      - "./dev/data/tls:/app/tls"
      - "./dev/data/ds:/app/db"
    domainname: EXAMPLE.COM
  kdc:
    env_file:
      ./dev/dev.env
    environment:
      IAM_KADMINDIR: /app/kadmin-data
      IAM_SECRETSDIR: /app/secrets
    volumes:
      - "./dev/data/secrets:/app/secrets"
      - "./dev/data/kdc:/app/db"
      - "./dev/data/kadmin:/app/kadmin-data"
    domainname: EXAMPLE.COM
  kadmin:
    env_file:
      ./dev/dev.env
    volumes:
      - "./dev/data/kadmin:/app/db"
    domainname: EXAMPLE.COM
  dev:
    build:
      target: dev
    env_file:
      ./dev/dev.env
    volumes:
      - slaprun:/var/run/slapd
      - "./:/workspace:cached"
      - home:/me
    networks:
      - iamnet
  root-ca:
    build:
      target: ca
    networks:
      - iamnet
    env_file:
      ./dev/dev.env
    volumes:
      - "./dev/data/root-ca:/home/step"
    healthcheck:
      interval: 5s
  infra-ca:
    env_file:
      ./dev/dev.env
    volumes:
      - "./dev/data/infra-ca:/home/step"
    depends_on:
      - root-ca
    healthcheck:
      interval: 5s
  user-ca:
    env_file:
      ./dev/dev.env
    volumes:
      - "./dev/data/user-ca:/home/step"
    depends_on:
      - root-ca
    healthcheck:
      interval: 5s
volumes:
  home:
